name: publish-gh-packages
on:
  push:
    tags: ['v*']
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<'XML'
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${env:GITHUB_ACTOR}</username>
                <password>${env:GITHUB_TOKEN}</password>
              </server>
            </servers>
          </settings>
          XML
      - name: Deploy to GH Packages
        run: mvn -P publish-github -DskipTests clean deploy
